name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main  # Triggers workflow when code is pushed to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # ✅ Ensure pytest is installed
      - name: Run Tests
        run: |
          pytest tests/  # Ensure you have test cases inside a 'tests/' folder
      
  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your_dockerhub_username/fastapi-app .

      - name: Push Docker Image to Docker Hub
        run: docker push your_dockerhub_username/fastapi-app

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull your_dockerhub_username/fastapi-app
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker run -d -p 8000:8000 --name fastapi-container your_dockerhub_username/fastapi-app
